version: '2'
services:
  openvpn:
    cap_add:
      - NET_ADMIN
    build: ./openvpn/docker
    container_name: openvpn
    ports:
      - "3128:3128"
      - "1080:1080"
    env_file: ./openvpn/settings/openvpn.env
    devices:
      - "/dev/net/tun:/dev/net/tun"
    restart: always
    volumes:
      - ./openvpn/settings/conf:/etc/openvpn:ro
    logging:
      driver: json-file
      options:
          max-size: "10m"
          max-file: "5"
